// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-mail-groups.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_mail_groups_default = defineTool({
  name: "list_mail_groups",
  title: "List mail groups",
  description: "List all mail groups belonging to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("mail_groups").select("id, name, description, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { groups: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-mail-group.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_mail_group_default = defineTool2({
  name: "create_mail_group",
  title: "Create mail group",
  description: "Create a new mail group for the signed-in user.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Group name"),
    description: z.string().trim().optional().describe("Optional description")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("mail_groups").insert({ user_id: ctx.getUserId(), name, description: description ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created group ${data.id}` }],
      structuredContent: { group: data }
    };
  }
});

// src/lib/mcp/tools/list-group-members.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_group_members_default = defineTool3({
  name: "list_group_members",
  title: "List group members",
  description: "List all members (recipients) of a specific mail group.",
  inputSchema: {
    group_id: z2.string().uuid().describe("Mail group ID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("group_members").select("id, email, name, created_at").eq("group_id", group_id).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { members: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sent-emails.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_sent_emails_default = defineTool4({
  name: "list_sent_emails",
  title: "List sent emails",
  description: "List recent emails sent by the signed-in user.",
  inputSchema: {
    limit: z3.number().int().positive().max(100).optional().describe("Max rows (default 25)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("sent_emails").select("id, subject, recipient_count, status, sent_at, scheduled_at, group_id").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { emails: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hkzqcdagdyrszhzleski";
var mcp_default = defineMcp({
  name: "smartmail-mcp",
  title: "SmartMail",
  version: "0.1.0",
  instructions: "Tools for the signed-in SmartMail user: list and create mail groups, list group members, and list sent emails.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_mail_groups_default, create_mail_group_default, list_group_members_default, list_sent_emails_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
